In [1]:
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [3]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


In [4]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))


Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [13]:
import numpy as np
A = np.ones((3,3))
B = np.arange(3)
print("Original array:")
print("Array-1")
print(A)
print("Array-2")
print(B)
print("A + B:")
new_array = A + B
print(new_array)

Original array:
Array-1
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array-2
[0 1 2]
A + B:
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [14]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.58855233 0.38246485 0.9651146  0.17922029 0.12663971 0.94532177
  0.57575311 0.72711023 0.8106806  0.56201037]
 [0.18139806 0.45265541 0.78324905 0.21290274 0.89176437 0.53624428
  0.3732765  0.37671183 0.27589248 0.2629564 ]
 [0.89642699 0.54352398 0.26507859 0.79496194 0.39170487 0.97246494
  0.29999092 0.34601602 0.42313555 0.2974918 ]
 [0.39041254 0.40918362 0.52147914 0.77848968 0.62857254 0.4401351
  0.62981199 0.36867222 0.09921221 0.11976905]
 [0.10426416 0.25698666 0.40530381 0.72116515 0.08507755 0.59380122
  0.01866506 0.02115808 0.9031019  0.12336009]]

Subtract the mean of each row of the said matrix:

[[ 0.00226554 -0.20382193  0.37882782 -0.4070665  -0.45964708  0.35903499
  -0.01053368  0.14082344  0.22439382 -0.02427641]
 [-0.25330705  0.0179503   0.34854394 -0.22180237  0.45705926  0.10153917
  -0.06142861 -0.05799328 -0.15881263 -0.17174871]
 [ 0.37334744  0.02044442 -0.25800097  0.27188238 -0.13137469  0.44938538
  -0.22308864 -0.17706354 -0.09